// Generated by CoffeeScript 1.4.0
var fs = require('fs');
var exec = require('child_process').exec;

exports.assertPathsExist = function(paths, done) {
  var c, l, maybeCallback;

  maybeCallback = function() {
    c++;
    if (c === l) {
      done();
    }
  };

  l = paths.length;
  c = 0;

  paths.forEach(function(path) {
    fs.exists(path, function(exists) {
      ("" + path + ":" + exists).should.equal("" + path + ":true");
      exists.should.equal(true);
      maybeCallback();
    });
  });
};

exports.generate = function (opts, done) {
  exec(__dirname + "/../../bin/ember-generate " + opts, function(err) {
    if (err) throw new Error(err);
    done();
  });
};

